sonar.projectKey=2023100283-ucss_restaurante-api-quality
sonar.organization=2023100283-ucss

# Nombre que aparecerá en el panel de Sonar
sonar.projectName=restaurante-api-quality
sonar.projectVersion=1.0

# Indicamos que el código está en la carpeta actual
sonar.sources=.
sonar.python.version=3
sonar.language=py

# Excluir carpetas que no necesitamos analizar (opcional pero recomendado)
sonar.exclusions=**/tests/**, **/docs/**
sonar.sourceEncoding=UTF-8